### ISSUE TITLE
Reduce Porcupine v1.9 WASM file memory allocation from 256MB to 20MB?

### ISSUE THREAD

**Issue by fquirin** [Picovoice/porcupine#666] opened 2022-02-10 19:53 UTC
When using the v1.9 WASM file for Porcupine you have to have a lot of free memory to avoid `RangeError: WebAssembly.Memory(): could not allocate memory`. This is due to the enormous 256MB requirement to instantiate the WASM module.
Typically on a 1GB machine Chromium browser will reserve around 350MB for WebAssembly that has to be shared with other libraries meaning the chances are high that the next call to allocate WebAssembly memory will fail. I'm running Porcupine with 2 additional other WASM modules and thus cannot start v1.9 on my Raspberry Pi 3 :-(.

Older Porcupine versions used only 16MB (v1.4 to v1.6) and v2 seems to move around 64MB with a dynamic max of 128MB, so I don't really see why v1.9 should require 2-10 times that amount.

Now I know that you're probably not interested in updating old versions but v1.9 is the last version that worked completely offline (without access key activation) and maybe you could make an exception and quickly compile the module again with a different `INITIAL_MEMORY` (or old version: TOTAL_MEMORY) flag? (I hope its that easy ^^). That would be awesome :pray: :slightly_smiling_face: 

Happy for any comments,
Florian

**Comment by kenarsa** [comment] 2022-02-11 15:16
thank you @fquirin ... We def look into it for V2.1 and subsequent releases.

**Comment by fquirin** [comment] 2022-02-11 20:22
Looking forward to it :slightly_smiling_face: 
I'm assuming that means no chance for a v1.9.1 release right? :sweat_smile:

**Comment by kenarsa** [comment] 2022-02-11 20:32
I cant see how we can allocate resources to an older version right now :)

**Comment by fquirin** [comment] 2022-02-11 20:58
I understand and I know how hard it is to maintain older versions :disappointed: . There are probably not many people still using the 1.9 WASM files, but keep in mind that not all of your users (and customers) will always be able to update right away! Especially not to new major versions.

I'd offer to fix it for you but that's probably impossible considering that this would require access to closed-source code.
Also I've no idea how complicated it actually is, I was just hoping that you might have a snap-shot of everything in your internal code repository and simply have to change the emscripten build flags ... most likely a very naive assumption :see_no_evil:

**Comment by kenarsa** [comment] 2022-02-11 21:00
@fquirin we are hiring software engineers ;)

**Comment by fquirin** [comment] 2022-02-11 21:43
Tempting, I have to admit :grin: , unfortunately I'm not free atm ;-)

**Comment by mrrostam** [comment] 2022-03-01 18:44
I believed the issue is fixed in the new porcupine npm packages (2.1.4). So we even have gone lower than before by asking for 8MB memory. Can you please test them out and see if that solves your problem with memory allocation?

**Comment by fquirin** [comment] 2022-03-03 13:18
Some of my users reported that v2.0 was already working on RPi3. I couldn't test it because I still have to wait until I can activate new devices again.
I'll try to update to v2.1 when I have time. Btw it doesn't really help that v2.0 and v2.1 keywords are incompatible :-/. I will have to tell my users to generate all custom keywords again with v2.1 or maintain both versions ...

Nevertheless the issue is more about v1.9 or removing the access-key dependence from v2+ for built-in keywords since many SEPIA devices have to work completely offline and users that value privacy usually have a problem with pinging a 3rd party server every now and then.

**Comment by mrrostam** [comment] 2022-03-03 15:13
Regarding the incompatibility of the keywords, I see your point. Still, whenever there is an improvement in the core engine to enhance the performance and accuracy, we have to move to a new version of keywords as well, and it's nothing new. It's been like this since v1.0.

As for the AccessKey issue, unfortunately, there is nothing that we can do at this moment to solve the mentioned problem with completely offline users.

**Closed** 2022-03-03 15:36 UTC
Labels: enhancement

**Comment by fquirin** [comment] 2022-03-03 16:01
> whenever there is an improvement in the core engine to enhance the performance and accuracy, we have to move to a new version of keywords as well

That's what I thought. I've followed the changes from 1.4 to 2.0 closely and it was pretty obvious that there were major changes happening. I just hoped that the 2.x series would be easier to update ^^.

> As for the AccessKey, unfortunately, there is nothing that we can do at this moment to solve the mentioned issue with completely offline users.

I understand. It must be pretty difficult to be "open" without negatively affecting commercially business. I wonder though how do you manage access on devices that have no network connection like some of the micro-controllers you support (I'm assuming there are a few)?

**Comment by fquirin** [comment] 2022-03-10 16:40
>  So we even have gone lower than before by asking for 8MB memory

@mrrostam do you know if this setting works with v2.0 as well ? To be more specific the question is would you expect the web-factory v2.1.4 to still work with the old v2.0 WASM. I've done some initial tests and it seems to work, I'm just not sure if its stable.

**Comment by mrrostam** [comment] 2022-03-10 20:15
> @mrrostam do you know if this setting works with v2.0 as well ? To be more specific the question is would you expect the web-factory v2.1.4 to still work with the old v2.0 WASM. I've done some initial tests and it seems to work, I'm just not sure if its stable.

We have not tested it, to be honest, and since v2.0, there have been some significant changes to the binding; hence there is no guarantee for that to work flawlessly. As a hacky solution, I'd recommend looking at the pr (([#675](https://github.com/Picovoice/porcupine/pull/675)) and applying the same changes to the package version you are working with.
