### ISSUE TITLE
Flutter Demo Crash

### ISSUE THREAD

**Issue by jtdLab** [Picovoice/porcupine#454] opened 2021-07-21 22:17 UTC
Problem: Demo App Crashes with Exited (sigterm) 

Device: IPhone 11 Pro Simulator (ios 13.2)

Steps to reproduce:
1. Launch App
2. Choose a keyword e.g "alexa"
3. Press Start-Button
After 15 - 20 seconds the app crashes

Flutter Doctor:

Flutter (Channel stable, 2.0.5, on macOS 11.4 20F71 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

**Comment by laves** [comment] 2021-07-24 00:11
@jtdLab, we were able to reproduce on iOS 13.2 simulator. We'll look into this ASAP. Thanks for reporting.

**Comment by laves** [comment] 2021-07-26 18:53
@jtdLab, we traced this error to the iOS audio recording module. Turns out this is a [known issue with iOS < 14 simulators](https://developer.apple.com/forums/thread/667921). Since this is not an issue with the Porcupine Flutter package, but an XCode/iOS simulator issue, I'm going to close this.

**Closed by laves** 2021-07-26 18:53 UTC
Labels: bug
