### ISSUE TITLE
Initialization of Porcupine failed

### ISSUE THREAD

**Issue by Ab-Appletic** [Picovoice/Porcupine#51] opened 2018-07-16 15:50 UTC
`ai.picovoice.porcupinemanager.PorcupineManagerException: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization of Porcupine failed.`

```
String keywordFilePath = new File(this.getFilesDir(), filename + ".ppn")
                .getAbsolutePath();
        String modelFilePath = new File(this.getFilesDir(), "params.pv").getAbsolutePath();
        try {
            manager = new PorcupineManager(modelFilePath, keywordFilePath, sensitivity, new KeywordCallback() {
                @Override
                public void run(int keyword_index) {
                    Toast.makeText(MainActivity.this, "Detected!", Toast.LENGTH_LONG).show();
                }
            });
            manager.start();
        } catch (PorcupineManagerException e) {
            e.printStackTrace();
            Log.e("Porcupine",e.getMessage());
        }

I have manually checked if keywordFilePath and modelFilePath are correct, and they are. This also happens in your demo application.
```

**Comment by kenarsa** [comment] 2018-07-16 18:37
this is a duplicate of https://github.com/Picovoice/Porcupine/issues/48
follow your issue there. closing ...

**Closed by kenarsa** 2018-07-16 18:37 UTC
Labels: duplicate
