### ISSUE TITLE
[ERROR] Unable to resolve dependency for ':porcupinemanager@debug/compileClasspath': Could not resolve project :porcupine.

### ISSUE THREAD

**Issue by wjdgy3746** [Picovoice/Porcupine#60] opened 2018-07-31 01:24 UTC
### Expected behavior
I downloaded project .zip file from github, and tried to execute demo/andriod/app in Android Studio.
However, Gradle project sync failed.
Please help me!

### Actual behavior
**Error messages are below**
Unable to resolve dependency for ':porcupinemanager@debug/compileClasspath': Could not resolve project :porcupine.
Unable to resolve dependency for ':porcupinemanager@debugAndroidTest/compileClasspath': Could not resolve project :porcupine.
Unable to resolve dependency for ':porcupinemanager@debugUnitTest/compileClasspath': Could not resolve project :porcupine.
Unable to resolve dependency for ':porcupinemanager@release/compileClasspath': Could not resolve project :porcupine.
Unable to resolve dependency for ':porcupinemanager@releaseUnitTest/compileClasspath': Could not resolve project :porcupine.

### Steps to reproduce the behavior
download zip file and execute in Android Studio

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by kenarsa** [comment] 2018-07-31 01:48
how did you open the project? please provide detailed steps so I can help.

**Comment by wjdgy3746** [comment] 2018-07-31 04:34
Hello!
I open the project by Android Studio-> File -> Open-> and select the porcupine-master folder at Open file or Project window.

**Comment by kenarsa** [comment] 2018-07-31 06:32
You need to open /demo/android. Please have a look at README there as well: https://github.com/Picovoice/Porcupine/tree/master/demo/android

**Comment by wjdgy3746** [comment] 2018-08-01 01:35
The Problem isn't solved.
I already open /demo/android, but it was not working. 
I also read README and created porcupine-debug.aar and added as dependency.

Error message is
Unable to resolve dependency for ':porcupinemanager@debug/compileClasspath': Could not resolve project :porcupine.

Could you help me to solve this problem?

**Comment by kenarsa** [comment] 2018-08-01 02:11
I am fairly certain that Android binging and demo app are working. But let's try to find the problem here. I need you to outline every single step to open/run the project so I can try to find the problem. thank you.

**Comment by wjdgy3746** [comment] 2018-08-01 02:59
Thank you.
These are the step to open and run the project.

1. I open 'Porcupine->binding->android' and build. 
2. I get 'porcupine-debug.aar' file in 'Porcupine->binding->android->porcupine->build->outputs->aar'
3. I open 'Porcupine->demo->android'
4. I add porcupine-debug.aar module by 'File->New Module->Import .JAR/.AAR Package'
5. Then, Gradle project sync failed, and Error message comes. 

This is project structure.
![image](https://user-images.githubusercontent.com/34389660/43498467-0d6f200c-9582-11e8-990b-5dc337d3e8ba.png)

 This is build process
![image](https://user-images.githubusercontent.com/34389660/43498514-42b1b568-9582-11e8-8489-b3211654139a.png)

![image](https://user-images.githubusercontent.com/34389660/43498549-5f6460de-9582-11e8-9a0b-ccc4b3f00b5f.png)

**Comment by kenarsa** [comment] 2018-08-01 03:03
OK. Can you please revert all local changes (or get a fresh version of repo). Only open the demo/android project (don't try to build anything manually) and then build that?

**Comment by wjdgy3746** [comment] 2018-08-01 03:38
I got a fresh version of repo.
And only open demo/android project.
Results are following.
![image](https://user-images.githubusercontent.com/34389660/43499701-c90c3dae-9587-11e8-8a3c-43cf0a3740c3.png)
@kenarsa

**Comment by kenarsa** [comment] 2018-08-01 03:48
what is the version of android studio you are using? what version of gradle? whats the OS?

I am using androidstudio 3.1.3 and cannot reproduce the problem.

**Comment by kenarsa** [comment] 2018-08-01 04:29
OK. I am building on a Linux box. That is the only difference. Can you build on Linux/Mac?

**Comment by wjdgy3746** [comment] 2018-08-01 04:54
OK. I build on Ubuntu by using VMware Workstation, but same error occurred.

**Comment by kenarsa** [comment] 2018-08-01 14:18
Let me think about how to go about debugging this as I need a way to reproduce it. One last question, when you've built on VM did you clone the repository directly into your VM and copied it from your Windows machine?

**Comment by wjdgy3746** [comment] 2018-08-02 00:13
I use the shared folder with Windows machine and VM. I clone the repository and put it in shared foloder.

I try to solve this problem, and another error occurred!
Now I can run the project in emulator. But when I press the START Button, the app is closed.
Logs are following
![image](https://user-images.githubusercontent.com/34389660/43555205-c890d6a8-9633-11e8-99b2-98070a615628.png)

Porcupine.java:28 is "System.loadLibrary("pv_porcupine");".
![image](https://user-images.githubusercontent.com/34389660/43555303-5caee42e-9634-11e8-88e2-8b7119c54615.png)

I think project can not load pv_porcupine library.
I tried System.load("direct path"); , but it was still not working.

And there is one more question. How can i figure out which OS i'm using such as arm64-v8a, armeabi-v7a, x86, x86_64?

**Comment by kenarsa** [comment] 2018-08-02 00:17
I think I know what the problem is. The project is using symlinks and when you clone it on a Windows machine it probably gets messed up! This is my hunch. An easy test would be to clone from VM directly without Windows involved. Could you give this a try?

Also, Android machinery figures what is your CPU and loads the correct binary.

**Comment by wjdgy3746** [comment] 2018-08-02 03:00
I clone from VM directly and open in Android Studio.
But modules cannot be loaded.
This is pop-up window.
![image](https://user-images.githubusercontent.com/34389660/43560012-89f2c7e0-964b-11e8-9650-40a50b9faf93.png)

I think there is problem with .iml files.

**Comment by ShannonHall** [comment] 2018-08-07 08:35
Hello, i have been facing this same problem. The first time I cloned and installed the repo it worked like a charm. I have since formatted and now i have this same problem. You may be correct about the symlinks. When i look in the demo/android directory, there is no folder labeled porcupine where when i had the project working i think there once was.

I cloned the repo, installed a fresh version of android studio and the error occurs.
Could not resolve project :porcupine.

**Comment by kenarsa** [comment] 2018-08-07 15:31
Hello @ShannonHall, Are you using Windows? Also maybe you can invalidate the cache of AndroidStudio and restart it.

**Comment by ShannonHall** [comment] 2018-08-07 22:31
Yes i am using widows 10, i have done Invalidate Cache/ Restart with no change.

**Comment by wjdgy3746** [comment] 2018-08-08 02:42
I run it using linux and it works! I think there may be a problem running in windows.

**Comment by kenarsa** [comment] 2018-08-08 02:44
Thanks. I think the issue is that Windows does not handle symlinks properly. Thanks for helping to debug. Sorry for the inconvenience. I will add this to DOC so that people know about this till we find a long-term solution.

**Comment by ShannonHall** [comment] 2018-08-08 10:34
This I can also confirm its working on Ubuntu 18.04.

**Comment by kenarsa** [comment] 2018-08-08 14:35
Thank you @wjdgy3746  and @ShannonHall  I am closing the issue and adding a NOTE to documentation that Android demo currently works on Linux and Mac.

**Closed by kenarsa** 2018-08-08 14:35 UTC

**Comment by crossplatformdev** [comment] 2018-10-12 15:33
I am working on my own different project and I can confirm that symbolic links DOES NOT WORK on windows 10. I just landed here reasearching about not working symlinks in Android Studio.

I have a project with its dependencies symlinked inside the folder of the main app project, so I could just add its dependencies and gradle.build files with shorter paths (that was my thought at first) but Android Studio is unable of 'enter across' symbolic links, no matter if they are hard or soft links.

Substituting link's paths by actual dependencies path's does indeed solve the problem.

I am using version 3.2.1 of Android Studio.
