### ISSUE TITLE
Porcupine Issue: pvporcupine._porcupine.PorcupineRuntimeError

### ISSUE THREAD

**Issue by Wapeto** [Picovoice/porcupine#961] opened 2023-04-27 12:29 UTC
I want to implement porcupine inside my project and to do so I followed all of the instrutions on the website, but when I try to run it, I get this error :

`Traceback (most recent call last):
  File "<path>", line 9, in <module>
    porcupine = pvporcupine.create(access_key=access_key, keywords=["computer"])
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineRuntimeError`

My whole code is pretty simpled and from the website :
```
porcupine = pvporcupine.create(access_key=access_key, keywords=["computer"])
recoder = PvRecorder(device_index=0, frame_length=porcupine.frame_length)

try:
    recoder.start()

    while True:
        keyword_index = porcupine.process(recoder.read())
        if keyword_index >= 0:
            print(f"Detected smth")

except KeyboardInterrupt:
    recoder.stop()
finally:
    porcupine.delete()
    recoder.delete()
```

I also tried different keywords and even made my own one from the website then downloaded it, but every time I get the same error message.

I am on Windows 11 with python 3.10.11 and porcupine 2.2.0

**Comment by mrrostam** [comment] 2023-04-27 17:55
Thank you for your report. Would it be possible for you to send us the AccessKey used to run the mentioned code to `hello@picovoice.ai`?

**Comment by Wapeto** [comment] 2023-04-27 18:09
It is : rQ1MRzeEIpkPna5pCCHLJKPpaxPR9ypM13UUL7Fih4+WrDHl1NlDSA==

**Comment by Wapeto** [comment] 2023-04-27 18:11
I am not allowed to send it, my message gets deleted

**Comment by Wapeto** [comment] 2023-04-27 18:12
Done

**Comment by Wapeto** [comment] 2023-04-27 18:13
> Thank you for your report. Would it be possible for you to send us the AccessKey used to run the mentioned code to `hello@picovoice.ai`?

Done

**Comment by mrrostam** [comment] 2023-04-27 18:14
Thank you for providing your AccessKey. However, it is not advisable to share it on Github as it can be utilized by anyone, and that's why I removed it.

**Comment by Wapeto** [comment] 2023-04-27 18:15
Yes I understand, I had forgotten sorry

**Comment by Wapeto** [comment] 2023-04-28 09:43
@mrrostam So do you know what might be causing this error ?

**Comment by mrrostam** [comment] 2023-04-28 18:52
Hey @Wapeto, my apologies for the delay in getting back to you. I wanted to double-check everything on our end to make sure our servers weren't causing the issue. It turns out that we don't have any logs of your access_key on our servers, so it seems like the issue might be on your end. Are you using Windows? If so, could you try running Porcupine on a terminal with admin privileges?

**Comment by Wapeto** [comment] 2023-05-01 13:43
I am using windows and running it from an admin terminal

**Comment by mrrostam** [comment] 2023-05-02 17:32
Unfortunately, despite several attempts, I have been unable to reproduce the issue on my end. Since it is a runtime error, it will be very difficult to determine the exact root cause of the problem without access to a similar system. As a final request, could you please check whether the `.pv` folder is located in your home directory?

**Comment by mrrostam** [comment] 2023-05-03 13:37
> Yes the .pv folder is in my home directory : C:/Users/User
> 
> Do you think the problem comes from my access_key ? And in that case could it be possible to get a new one ?

No, your AccessKey is not the issue. It appears that there is a problem with the system you are using, which is causing a runtime error.

**Comment by mrrostam** [comment] 2023-05-03 18:18
We did some more investigation, and finally discovered what's causing the issue you're having with your Windows system. Unfortunately, we can't fix it right away. You'll have to wait for us to update the library file and Python packages. I'll keep the issue report open until the new library is released with the fix. Sorry for any inconvenience this may have caused you.

**Comment by Wapeto** [comment] 2023-05-04 10:28
No problem I'll wait, please ping me when the new library is out

**Comment by xador70** [comment] 2023-05-27 02:39
I'm waiting for the fix. I would really appreciate it.

**Comment by laves** [comment] 2023-06-07 22:42
Hello folks - thank you for your patience. We've released a patch that should address this issue. Upgrade `pvporcupine` to `2.2.1` to grab the release.

**Closed** 2023-06-12 17:15 UTC
Labels: bug
