### ISSUE TITLE
Java init fails on Linux mint

### ISSUE THREAD

**Issue by Blu3Lif3** [Picovoice/porcupine#686] opened 2022-03-16 17:32 UTC
Im trying to create an home assistant with a laptop x86_64 running Raspberry Os. Of I try to run my code i get this Error:
`ai.picovoice.porcupine.PorcupineIOException: Initialization failed.
at ai.picovoice.porcupine.Porcupine.init(Native Method)
at ai.picovoice.porcupine.Porcupine.<init>(Porcupine.java:61)
at ai.picovoice.porcupine.Porcupine$Builder.build(Porcupine.java:262)
at de.VoiceRecognition.ball.WakeWordDetection.main(WakeWordDetection.java:79)`

this is my code:

`
            
           
                    
            ByteArrayOutputStream outputStream = null;

        
            String Keypath =   "voiceTickets/de_linux_v2_1_0.ppn";
            String ModelPath = "voiceTickets/porcupine_params_de.pv";
            
            // get audio capture device
            
            
            try {
                micDataLine = mic.getTargetDataLine();
                micDataLine.open(format);
            } catch (LineUnavailableException e) {
                System.err.println("Failed to get a valid capture device. Use --show_audio_devices to " +
                        "show available capture devices and their indices");
                System.exit(1);
                return;
            }
            

                Porcupine handle = new Porcupine.Builder()
                                    .setAccessKey(accessKey)
                                    .setKeywordPath(Keypath)
                                    .setModelPath(ModelPath)
                                    .build();`
Thank You

**Comment by ksyeo1010** [comment] 2022-03-17 20:21
Based on the error, it seems that the path you provided for the `ModelPath` or `Keypath` is incorrect. Can you make sure those are correct paths? Also, If you run the program, you can see a more detailed error message in the console describing your issue.

**Comment by Blu3Lif3** [comment] 2022-03-21 15:40
Above the error appears when I stop the code a green text
`[INFO] Porcupine model path: 'voiceTickets/porcupine_params_de.pv' 
`
` [INFO] Porcupine keyword path[0]: 'voiceTickets/Karla_de_linux_v2_1_0.ppn`
` [INFO] Porcupine sensitivity[0]: 0,50`

**Comment by kenarsa** [comment] 2022-03-21 16:31
@Blu3Lif3 does these files exist?
```
[INFO] Porcupine model path: 'voiceTickets/porcupine_params_de.pv'
[INFO] Porcupine keyword path[0]: 'voiceTickets/de_linux_v2_1_0.ppn
```

I think the path to them might be incorrect. You can test it yourself with something like `.exists()`

**Comment by kenarsa** [comment] 2022-03-21 18:34
@Blu3Lif3 thank you! OK. The next I think we can do to help me out is to try to reproduce the same issue using one of the official [Java demos](https://github.com/Picovoice/porcupine/tree/master/demo/java). Can you please give it a try? Essentially I want to see if you can run the demo on your system as is successfully and if yes can you replace your model/keyword file and still have it working. I can help out more after learning about the outcome. keep me posted.

**Comment by Blu3Lif3** [comment] 2022-03-21 20:50
Thank you for ur help and advices. I will try it tomorrow because im ill. I will give u an update! 🙌 appreciate it man

**Comment by Blu3Lif3** [comment] 2022-03-22 15:43
@kenarsa Hey I have tried it now and I am getting this Error:
`oem:~/Desktop/demo/java/build/libs$ java -jar porcupine-mic-demo.jar -a [CODE] -k porcupine `
`[INFO] Porcupine model path: '/tmp/porcupine-mic-demo/porcupine/lib/common/porcupine_params.pv'`
`[INFO] Porcupine keyword path[0]: '/tmp/porcupine-mic-demo/porcupine/resources/keyword_files/linux/porcupine_linux.ppn'`
`[INFO] Porcupine sensitivity[0]: 0,50`
`ai.picovoice.porcupine.PorcupineActivationException: Initialization failed.`

**Comment by kenarsa** [comment] 2022-03-22 16:32
Hmmm ... that means tha the engine cannot verify your `AccessKey`. Do you have an internet connection? I am assuming you replaced `[CODE]` with your own `AccessKey` from Console?

**Comment by kenarsa** [comment] 2022-03-22 17:50
do you mind sending your AccessKey to me so we can debug it on our side? hello@picovoice.ai

**Comment by kenarsa** [comment] 2022-03-22 19:10
can you please give it another try?

**Comment by Blu3Lif3** [comment] 2022-03-22 19:21
> can you please give it another try?

Yess give me a minute

**Comment by Blu3Lif3** [comment] 2022-03-22 19:28
> can you please give it another try?

I've tried it

**Comment by kenarsa** [comment] 2022-03-22 20:42
? did it work...

**Comment by Blu3Lif3** [comment] 2022-03-22 21:55
No unfortunately not, Im getting the same Output in the Console

**Comment by kenarsa** [comment] 2022-03-23 04:01
I checked the server-side and everything looked good! Trying to brainstorm here ... Is your OS standard Ubuntu?

**Comment by Blu3Lif3** [comment] 2022-03-23 06:17
Its the new linux mint :)

**Comment by kenarsa** [comment] 2022-03-23 14:12
Got it! Any chance you can give it a try on standard Ubuntu? I am thinking if that makes a difference then at least I know what might break the process and help with debugging. thank you in advance :)

**Comment by Blu3Lif3** [comment] 2022-03-24 07:26
Yess i will Try it later no problem. I will write you when Im done, Thank You :)

**Comment by Blu3Lif3** [comment] 2022-03-24 17:26
Hey Im struggling with ubuntu it wont install on my partition, thats why it takes so long

**Comment by Blu3Lif3** [comment] 2022-03-24 18:16
Im now home i will try it on my Desktop PC with ubuntu, i hope this doesnt make any difference

**Comment by Blu3Lif3** [comment] 2022-03-25 09:57
I've run it via Ubuntu Standard with my Desktop PC!

**Comment by kenarsa** [comment] 2022-03-25 15:01
OK. So it runs successfully on Ubuntu standard but not on mint? Can you please confirm? If that is the case then I can start debugging it there.

**Comment by Blu3Lif3** [comment] 2022-03-25 15:10
Yes correct it runs on Ubuntu standard but not on mint

**Comment by kenarsa** [comment] 2022-03-25 15:15
Great. I changed the title to reflect the root cause and I will get someone to work on this. Aiming for a solution in the coming weeks.

**Comment by Blu3Lif3** [comment] 2022-03-25 15:16
Thank you man!  Habe a good one

**Comment by Blu3Lif3** [comment] 2022-03-25 19:37
Could you recommend me any linux system apart from ubuntu Standard for the ai?

**Comment by laves** [comment] 2022-03-25 21:34
@Blu3Lif3 - we just tried on Linux Mint 20.3 (Cinnamon Edition) and the Porcupine Java demo is working. At this point, we may have to close this issue based on our inability to reproduce. If you have any unusual settings/configuration on the Mint system you encountered the error on, let us know and we can try again.

**Comment by Blu3Lif3** [comment] 2022-03-25 21:54
Okay Thank you! May it be a problem that the CPU of the laptop is 64 bit with an 32 efi?

**Comment by laves** [comment] 2022-03-28 17:16
That definitely could create problems as the Linux binary is 64-bit only. That would be a configuration I'm comfortable saying that we don't support at this time. I'm going close this issue for now since we can't reproduce and/or do not support the machine configuration in question.

**Comment by laves** [comment] 2022-04-19 22:04
@Blu3Lif3 we were finally able to narrow down the cause of this issue and put in a fix for it. Your laptop that was encountering the error should now work for you.

**Comment by laves** [comment] 2022-04-19 22:21
I'm reopening this issue so that you can confirm the fix and close it once you've confirmed.

**Comment by laves** [comment] 2022-04-28 19:41
Closed due to inactivity

**Closed by laves** 2022-04-28 19:41 UTC
Labels: help wanted
