### ISSUE TITLE
Porcupine crash observed when multiple porcupine instances(handles) are used with multiple threads for keyword detection in multiple audio channels

### ISSUE THREAD

**Issue by arunnadesh** [Picovoice/Porcupine#31] opened 2018-06-07 12:52 UTC
Hi Alireza,
We ran into a porcupine crash, when we tried creating multiple porcupine handles for processing multiple audio streams simultaneously.

Steps to reproduce:
1.	The C/C++ Application spawns two threads and creates two porcupine handles(handle1 and handle2) for detecting keywords from two audio steams.
2.	The first thread finishes detection for the first audio stream and frees the porcupine handle using the method pv_porcupine_delete(handle1);
3.	But the second thread still continues feeding audio data to porcupine engine from second audio stream using handle2.
Here after the 3rd step, the application crashes with the following back-trace…

           #######
           6505== Invalid read of size 4
           6505==    at 0x40666A8: pv_sqrt (in /root/Arun/Porcupine-master/lib/linux/i386/libpv_porcupine.so)
           6505==    by 0x406439C: pv_specgram_compute (in /root/Arun/Porcupine-master/lib/linux/i386/libpv_porcupine.so)
           6505==    by 0x4063823: pv_mel_filter_bank_compute (in /root/Arun/Porcupine-master/lib/linux/i386/libpv_porcupine.so)
           ==6505==    by 0x40619C4: pv_porcupine_multiple_keywords_process (in /root/Arun/Porcupine-master/lib/linux/i386/libpv_porcupine.so)
           6505==    by 0x404AB38: start_thread (in /lib/libpthread-2.12.so)
           6505==    by 0x428ED6D: clone (in /lib/libc-2.12.so)
           ######

 Please note, the above crash doesn’t occur, when the second thread creates its porcupine handle after the first thread finishes the execution.
Could you please have a look at this issue and let us know the root cause and resolution?

Regards,
Arun

**Comment by kenarsa** [comment] 2018-06-08 16:31
Hi Arun,

The stack trace is quite helpful. Thanks. The problem is that the math module is shared between different instances of the objects and when the first one quits it also releases resources acquired by math module. We need to do some reference counting here or give each instance a different instance of math module. I will add this to our TODO list and will push it out for next release. But it will take us a while to get to it considering other priorities.

In the meantime. I can think of a couple of things you can do to not get blocked:

1- Make a copy of .so for each thread (not nice) but works for sure.
2- Have a pool of Porcupine instances that you never delete (like ThreadPool but PorcupinePool!). Then you can assign them to new threads when you spawn them.

Let me know what you think.

Thanks a lot for helping us make Porcupine a better library.

**Comment by arunnadesh** [comment] 2018-06-08 17:43
Thanks for the response...I have already implemented the second solution... ☺️

**Comment by kenarsa** [comment] 2018-06-20 04:53
Hi Arun,

Could you please check and see if the issue is resolved in v1.3?

Thanks

**Comment by arunnadesh** [comment] 2018-06-22 11:28
Thanks... I will check and update...

**Comment by kenarsa** [comment] 2018-07-16 18:16
any updates?

**Comment by kenarsa** [comment] 2018-07-22 21:10
closing due to inactivity. feel free to reopen if the issue is not resolved.

**Closed by kenarsa** 2018-07-22 21:10 UTC
