### ISSUE TITLE
Porcupine Android Sample App Hot Word Recognize issue

### ISSUE THREAD

**Issue by sushilkumar2007** [Picovoice/Porcupine#184] opened 2019-06-10 13:05 UTC
### Steps to reproduce the behavior

Please include enough details so that the issue can reproduced independently by the resolver.

**Comment by sushilkumar2007** [comment] 2019-06-10 13:08
Sometimes it freezes and does not response of hot word three or four times we speak. random behavior

**Comment by kenarsa** [comment] 2019-06-11 14:44
duplicate of https://github.com/Picovoice/Porcupine/issues/185

Please do NOT open duplicate issues.

**Closed by kenarsa** 2019-06-11 14:44 UTC
