### ISSUE TITLE
The snowboy engine in Benchmark should be set as "ApplyFrontend=True"

### ISSUE THREAD

**Issue by eqiihuu** [Picovoice/Porcupine#170] opened 2019-05-03 21:25 UTC
### Expected behavior
After making the change ("ApplyFrontend=True"), the snowboy engine outperform all of the other 3 engines in the ROC curve.
![image](https://user-images.githubusercontent.com/13514412/57166486-3ce73300-6daf-11e9-9e3c-f5a03762ae13.png)

### Actual behavior
Snowboy engine currently is set to "ApplyFront=False" when running the Alexa benchmark, and this is not the optimized parameter.

### Steps to reproduce the behavior
Set to "ApplyFront=True" when running the snowboy Alexa benchmark. Add "self._snowboy.ApplyFrontend(True)" in the class SnowboyEngine in wakeword-benchmark/engine.py
![image](https://user-images.githubusercontent.com/13514412/57166498-496b8b80-6daf-11e9-8727-88c5b09c79a8.png)

**Comment by kenarsa** [comment] 2019-05-04 23:49
this is an exact duplicate of this ticket https://github.com/Picovoice/wakeword-benchmark/issues/4

**Closed by kenarsa** 2019-05-04 23:49 UTC
