### ISSUE TITLE
High CPU usage on Raspberry pi Zero W. SDK

### ISSUE THREAD

**Issue by esdrujulo** [Picovoice/porcupine#420] opened 2021-05-19 13:34 UTC
Hi all. Writing this to see if anyone found this issue.

Scenario:

Raspberry pi Zero WiFi. Python code that waits for the porcupine KeyWord (spanish Keyword):

```
   #...
   #keyword_paths
   model_path = '/home/pi/Aplicaciones/chatbot/keys/porcupine_params_es.pv'
   keyword_paths = ['/home/pi/Aplicaciones/chatbot/keys/leopardo_raspberry-pi.ppn']

   #pvporcupine handle
   def create_handle():
       global handle
       global audio_stream
       handle = pvporcupine.create(model_path=model_path,keyword_paths=keyword_paths)
       pa = pyaudio.PyAudio()
       audio_stream =  pa.open(rate=handle.sample_rate,channels=1,format=pyaudio.paInt16,input=True,
                               frames_per_buffer=handle.frame_length)
   create_handle()

   #Main loop
   while True:
       pcm = audio_stream.read(handle.frame_length)
       pcm = struct.unpack_from("h" * handle.frame_length, pcm)
       keyword_index = handle.process(pcm)
       if keyword_index >= 0:
           #Delete pvporcupine instance, since we won't use it any more
           handle.delete()
           print("Tell me...")
       else:
           #print("None...")
           #time.sleep(0.5)
           continue
    #...
```

All works well, but CPU usage while waiting the KeyWord is about 60% all time. Even in complete silence. Keyword recognition response time is very good, almost instant.

When playing background streaming radio channels (with VLC) and porcupine is waiting to recognize the KeyWord, music is crispy or stops, and recognition response time feedback increases for about 10 seconds.

Does anybody found this high CPU usage when using porcupine SDK?

Thanks in advanced.

**Comment by kenarsa** [comment] 2021-05-19 13:55
not a bug. the expected CPU usage on an RPI0 with Python SDK is about that. If you want lower CPU usage you should use the C SDK.

**Comment by esdrujulo** [comment] 2021-05-19 13:59
> ge on an RPI0 with Py

Thank you very much @kenarsa 

Will try the C SDK

**Comment by kenarsa** [comment] 2021-05-19 14:23
cool. closing for now. if you face problems with C SDK please open a new issue.

**Closed by kenarsa** 2021-05-19 14:23 UTC
Labels: question
