### ISSUE TITLE
Wrong counting of Activation Limit 

### ISSUE THREAD

**Issue by DanBmh** [Picovoice/porcupine#1312] opened 2024-09-20 15:26 UTC
Hi, I currently have the problem that my Activation Limit is not counted correctly.

I'm running Porcupine on a Linux Desktop Computer in a Docker container and after a few restarts of the container/pc I'm running into the `PorcupineActivationLimitError`:

```
|   File "/Jaco-Satellite/wake-word/action-ww.py", line 42, in load_keyword_listener
|     pcpn = pvporcupine.create(
|   File "/usr/local/lib/python3.8/dist-packages/pvporcupine/_factory.py", line 69, in create
|     return Porcupine(
|   File "/usr/local/lib/python3.8/dist-packages/pvporcupine/_porcupine.py", line 198, in __init__
|     raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
| pvporcupine._porcupine.PorcupineActivationLimitError: Initialization failed:
|   [0] Picovoice Error (code `00000136`)
|   [1] Picovoice Error (code `00000136`)
|   [2] Picovoice Error (code `00000136`)
```  

I think that the issue could be that every time I restart the docker container Porcupine thinks it's running on a new device.
And then after a few times, I can't use Porcupine anymore.

Is there any option how I can solve this?

**Comment by ksyeo1010** [comment] 2024-09-20 16:52
Duplicate of https://github.com/Picovoice/picovoice/issues/552.

**Closed by ksyeo1010** 2024-09-20 16:52 UTC
