### ISSUE TITLE
Porcupine throws runtime error on running 

### ISSUE THREAD

**Issue by OnlinePage** [Picovoice/porcupine#617] opened 2022-01-11 14:05 UTC
Hi, I have been trying to use porcupine in python with [pvpocrupine on PyPI](https://pypi.org/project/pvporcupine/), with a very basic example of instantiating the porcupine object with access_key and keywords, it throws an unknown runtime error.
Here is the code.

    
    import pvporcupine 
    
    # access_key = "${ACCESS_KEY}" # AccessKey obtained from Picovoice Console (https://picovoice.ai/console/)

    handle = pvporcupine.create(access_key="/6JE6BtRaWEQ8Y7DMhTXW5pUGXp9+WtA==", keywords=['porcupine'])
    #above access key is altered for security reason
this throws below error
   

      Traceback (most recent call last):

      File "c:\Users\Pranshu Ranjan\s2\actions\pic_again.py", line 43, in <module>

      handle = pvporcupine.create(access_key="/6JEWV7IWygsvGC0n9LSHQH60G6BtRaWEQ8Y7DMhTXW5pUGXp9+WtA==", 
      keywords=['porcupine'])
      File "C:\ProgramData\Anaconda3\lib\site-packages\pvporcupine\__init__.py", line 77, in create
      return Porcupine(
      File "C:\ProgramData\Anaconda3\lib\site-packages\pvporcupine\porcupine.py", line 158, in __init__
      raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
      pvporcupine.porcupine.PorcupineRuntimeError

system spec:- 
- anaconda environment
-  Windows 11 64 bit
- Python 3..6.6
- pvporcupine 2.0.4 

Earlier with pvporcupine 1.9.0, it runs flawlessly great.
Please let me know the possible fix to the above issue.

**Comment by kenarsa** [comment] 2022-01-11 14:23
the same document clearly asks you to keep your `AccessKey` secret:

```text
The Porcupine SDK requires a valid AccessKey at initialization. AccessKeys act as your credentials when using Porcupine SDKs. You can create your AccessKey for free. Make sure to keep your AccessKey secret.
```

**Comment by kenarsa** [comment] 2022-01-11 14:24
do you have internet connectivity? you do need to have connectivity to verify your `AccessKey`

**Comment by OnlinePage** [comment] 2022-01-14 01:46
> do you have internet connectivity? you do need to have connectivity to verify your `AccessKey`

Just waiting to know any possible fix for it!!

**Comment by kenarsa** [comment] 2022-01-14 01:57
Can you also install porcupine via PIP (not Conda) and verify you can reproduce it?

**Comment by OnlinePage** [comment] 2022-01-14 11:55
> Can you also install porcupine via PIP (not Conda) and verify you can reproduce it?

As u said I did install porcupine outside conda on windows, but the issue is the same, below is the screenshot of what I did.
![image](https://user-images.githubusercontent.com/61045650/149511414-e2dbb70b-f301-4c36-bf47-789886176139.png)

You can clearly see, this time I have installed porcupine without conda in the terminal and the following the basic instantiating the object of a porcupine. Any fix, please?

**Comment by laves** [comment] 2022-01-14 18:20
@OnlinePage we're going to look into this. Thanks for your patience.

**Comment by laves** [comment] 2022-01-14 21:17
@OnlinePage we are unable to reproduce this issue on a Windows 11 machine. The only thing that we can think of here is that you may have a non-standard environment variable set up. To check that, can you open Powershell and input the following two commands:
```powershell
echo $env:userprofile
echo $env:homedrive$env:homepath
```

One of these commands should print the value to your home user directory. If not, then that would cause the error.

**Comment by OnlinePage** [comment] 2022-01-15 06:50
> @OnlinePage we are unable to reproduce this issue on a Windows 11 machine. The only thing that we can think of here is that you may have a non-standard environment variable set up. To check that, can you open Powershell and input the following two commands:
> 
> ```powershell
> echo $env:userprofile
> echo $env:homedrive$env:homepath
> ```
> 
> One of these commands should print the value to your home user directory. If not, then that would cause the error.

Thanks again for your reply! I tried running the above command in windows Powershell, below is the screenshot of it.
![image](https://user-images.githubusercontent.com/61045650/149612332-a2838502-789a-4fb6-b4ab-08f5cb9dd00e.png)

You can see I am getting the home user directory as the output on both commands, still confused why it's not working 😣.
Whereas with porcupine version 1.9, it's running flawlessly great. Please, any workaround?

**Comment by laves** [comment] 2022-01-17 18:57
Okay, thank you - that disproves our original hunch. Unfortunately, since we can't reproduce this issue with the same setup, we can only ask you to perform some more diagnostic steps in order to narrow down the problem with your specific environment. Could you try turning off your internet and initializing Porcupine? If you get the same error, that will tell us a bit about where the error is being produced.

**Comment by OnlinePage** [comment] 2022-01-17 19:50
> 
Thanks again for incorporating so far, so I did as you said. I pulled off ethernet and tried running the same code, this time I got a different error. You can see the below screenshot for clarity.
![image](https://user-images.githubusercontent.com/61045650/149829671-c5571ea7-895b-4dd5-9331-04dd095d32ea.png)

**Comment by laves** [comment] 2022-01-17 21:51
Okay, this is helpful. We're starting to narrow down where this is occuring. Can you run the following Powershell cmd:
```powershell
(Get-CimInstance -Class Win32_ComputerSystemProduct).UUID
```
Does this return a UUID or something else for you?

**Comment by laves** [comment] 2022-01-18 01:24
@OnlinePage - we're pretty sure we now know what is causing this and will be addressing it in our next release. For now, a workaround for you would be to either remove/move the `profile.ps1` file located in your `Documents/WindowsPowerShell` folder or to enable the running of Powershell scripts on your system by opening Powershell as an administrator and running the following command:
```powershell
Set-ExecutionPolicy RemoteSigned
```

That should also remove that large bit of red text you get when you open your Powershell.

**Comment by OnlinePage** [comment] 2022-01-18 05:51
> 

Yeah, that returned a UUID here's the screenshot.
![image](https://user-images.githubusercontent.com/61045650/149878645-b610bdf5-d42e-45ed-b41e-c65c5eaabd4e.png)

**Comment by OnlinePage** [comment] 2022-01-18 05:57
> @OnlinePage - we're pretty sure we now know what is causing this and will be addressing it in our next release. For now, a workaround for you would be to either remove/move the `profile.ps1` file located in your `Documents/WindowsPowerShell` folder or to enable the running of Powershell scripts on your system by opening Powershell as an administrator and running the following command:
> 
> ```powershell
> Set-ExecutionPolicy RemoteSigned
> ```
> 
> That should also remove that large bit of red text you get when you open your Powershell.

Yeah I did run that command and enable the execution policies and now those red warnings are no more and bingo, the script is now running great!! 😎😀.
![image](https://user-images.githubusercontent.com/61045650/149879275-4dcfd2b3-79bf-4c66-8a36-2b4a901b9604.png)

 So I guess picovoice runs a PowerShell script in the backend since it was disabled that's why it was causing an error? can you just explain a little about it? Well, thanks again @laves and Picovoice team for working and finding the cause of the issue!! I hope you guys will mention and fix such scenarios in upcoming updates.

**Comment by laves** [comment] 2022-01-18 17:49
Great! I won't get into any specifics, but we don't run any Powershell script files. That block of error text however was making it's way into a system call we use. We'll be applying a permanent fix for this in the next release so that this should not effect future users. Thanks for bringing this to our attention!

**Closed by laves** 2022-01-18 17:49 UTC

**Comment by OnlinePage** [comment] 2022-01-18 18:20
> Great! I won't get into any specifics, but we don't run any Powershell script files. That block of error text however was making its way into a system call we use. We'll be applying a permanent fix for this in the next release so that this should not affect future users. Thanks for bringing this to our attention!

ya fine, thanks again! 😀😎😀

**Comment by prashantaarya** [comment] 2025-02-18 17:38
PorcupineActivationError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)

**Comment by Nico1657** [comment] 2025-04-09 11:00
Same error here:
PorcupineActivationRefusedError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)

even with:

![Image](https://github.com/user-attachments/assets/02871930-abb3-44e1-b6e0-c1a3d54193dc)

![Image](https://github.com/user-attachments/assets/55c06e58-0a04-4bab-8625-f2a1dc55ba76)

python==3.12.6
pvporcupine==3.0.5
Windows 10 64-bit
