### ISSUE TITLE
Sensitivity acting unexpectedly

### ISSUE THREAD

**Issue by bjg2** [Picovoice/Porcupine#134] opened 2018-12-26 12:32 UTC
### Expected behavior
Word recognized with sensitivity of x should be recognized with sensitivities bigger than x.

### Actual behavior
Word recognized for sensitivity of x might not be recognized for bigger sensitivities.

### Steps to reproduce the behavior
Create multiple Porcupine classes with different sensitivities (0-1). Detect PCM and process it with all Porcupine classes. Sometimes, it will happen that word recognized with Porcupine with some sensitivity is not recognized for some Porcupine with bigger sensitivity.

I want to use sensitivity as a threshold, and to know if word is recognized with some sensibility that it will be recognized with bigger one. Can I do that? Am I doing something wrong? Or is your sensitivity description wrong?

**Comment by bjg2** [comment] 2018-12-26 14:15
I changed your python demo a bit to showcase this problem: https://pastebin.com/8w5UJhMw

You can start it with any keyword example, you can see that it is not true that increased sensitivity recognizes the word that is recognized with lower sensitivity (as shown in screenshot attached).

![image](https://user-images.githubusercontent.com/6639273/50448344-fa08e080-0920-11e9-94f1-855caf91537c.png)

**Comment by kenarsa** [comment] 2018-12-27 18:19
Had a look at your code. Debugging this in a live situation will be very hard. I suggest the following: 
1- Record a WAV file with your keyword in it. You can say it multiple times.
2- Use the offline demo (it is a different file in the same folder) to process WAV with different sensitivity

Can you please do the above?

With current demo I am not sure if the problem is with the porcupine, running multiple instances of it at the same time (this should be OK), or a runtime issue (not being able to process in time).

**Comment by bjg2** [comment] 2018-12-28 15:01
I cannot reproduce, and I don't understand what might be the cause. This is what I tried:
* In the same code I gave to you, I printed PCM data all the time until the bad porcupine state is reached
* I inserted that same PCM data in the loop instead of listening to the mike
* Porcupine is not giving wrong results anymore but meaningful ones

I totally don't understand what is happening here... How do you mean not able to process in time, I don't give it any time limit and wait until porcupine process finishes?

Code (with the PCM data, commented part is about taking PCM data): https://paste.ofcode.org/WpiichpQTwYWqkq8cb5gnc
First output (problematic cause bigger ): [False, False, True, True, False, False, False, False, False, False]
Repeated output (doesn't repro the issue): [False, False, False, False, True, True, True, True, True, True]

**Comment by kenarsa** [comment] 2018-12-29 18:02
Yeah. This is good as the engine is working as expected.

Not being able to process on time means that maybe running ten instances of Porcupine at the same time is not possible on your machine in real-time. I am not sure what is the cause in your real-time test.

But the sensitivity is working as expected, right?

I am going to close the issue. If you can't figure the root cause in your first test open another issue with the relevant topic. Thanks!

**Closed by kenarsa** 2018-12-29 18:02 UTC

**Comment by bjg2** [comment] 2019-01-08 15:20
Sorry I didn't reply earlier, there were holidays in Serbia. Still, I don't understand, as I don't run them at the same time but one by one (there's no parallelism in the code).

Anyway, the thing I'm trying to do all this time is to get the confidence of the word recognition. In my mind, confidence = 1 - sensitivity, so I'm trying to get the lowest sensitivity that recognizes the given audio input as any word and deduce confidence out of it. I was trying to do binary search on sensitivity, but I failed because of the issues with determinism mentioned above.

I tried another solution around this problem, that seems to work better:
* Input is list of keyword_file_paths (list of files to recognize) and conf_steps (number of different sensitivities to check). Example: list of 3 words and 100 probability steps.
* Generate keyword_file_paths from provided one by repeating it conf_steps times. Example: [word1, word2, word3, word1, word2, word3, word1, word2, word3...]
* Generate sensitivities by repeating sensitivity step number of keywords times. Example: [0, 0, 0, 0.01, 0.01, 0.01, 0.02, 0.02, 0.02....]
* This way we have each sensitivity for each word, sorted ascending by sensitivity, and `the first  keyword+sensitivity combination recognized will be returned`

This seems to work good enough, I need you to comment on `the first  keyword+sensitivity combination recognized will be returned` part - is that true? If that is true, out of the processing return I can know the word recognized and the lowest sensitivity for recognizing that word.

Thanks for your time! Aleksandar
