### ISSUE TITLE
Porcupine Issue: npm install failing for web demo on Windows

### ISSUE THREAD

**Issue by blakebullwinkel** [Picovoice/porcupine#876] opened 2023-01-13 07:51 UTC
I am trying to run the web demo of Porcupine on Windows. 

### Expected behaviour

After cloning into the repository and running:
```
cd porcupine/demo/web
npm install
```
packages should install without errors.

### Actual behaviour

After running `npm install`, I get

```
> porcupine-web-demo@2.1.0 postinstall
> npx pvbase64 -i ../../lib/common/porcupine_params.pv -o ./porcupine_params.js && cp ../../resources/keyword_files/wasm/porcupine_wasm.ppn ./

Encoding '../../lib/common/porcupine_params.pv'
Done! Saved file to './porcupine_params.js'.
'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\jblak\Documents\porcupine\demo\web
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx pvbase64 -i ../../lib/common/porcupine_params.pv -o ./porcupine_params.js && cp ../../resources/keyword_files/wasm/porcupine_wasm.ppn ./

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jblak\AppData\Local\npm-cache\_logs\2023-01-13T07_44_58_102Z-debug-0.log
```

### Steps to reproduce the behaviour

On Windows, simply clone the Porcupine repo `git clone --recurse-submodules https://github.com/Picovoice/porcupine.git`

and run

```
cd porcupine/demo/web
npm install
```

**Comment by mrrostam** [comment] 2023-01-13 19:54
Thank you for reporting; the issue is fixed now and the web demo should run flawlessly on Windows.

**Closed** 2023-01-14 17:56 UTC
Labels: bug
