### ISSUE TITLE
Porcupine Issue: Unable to start speech Recognition after porcupine wake word

### ISSUE THREAD

**Issue by vp2305** [Picovoice/porcupine#415] opened 2021-05-07 19:12 UTC
Hey guys I'm trying to make a voice assistant which works more like google assistant. I want to trigger the listening after porcupine has successfully determined the wake word. I understand there cant be two services listening to the audio at the same time. So I have tried to stop the porcupineManager.stop() (To stop from porcupine to listen) then initialized speech recognition and to start listening for the input again, but for some reason after porcupineManager.stop() it doesn't go to the next line. I looked at the onDestory method and commented out porcupineManager.delete() because maybe that was causing it but that wasn't the case as well. I will really appreciate if anyone can help me out here. 

    ` try {
                Log.i("YOU SAID IT!", "yesss");
                porcupineManager = new PorcupineManager.Builder()
                        .setKeyword(Porcupine.BuiltInKeyword.JARVIS)
                        .setSensitivity(0.7f).build(
                                getApplicationContext(),
                                (keywordIndex) -> {
                                    Log.i("bshdbsdh", "sdsd");
                                    // This is where I need to somehow stop so that I can trigger speech recognition to listen
                                    userInputListener();
                                    numUtterances++;

                                PendingIntent contentIntent = PendingIntent.getActivity(
                                        this,
                                        0,
                                        new Intent(this, MainActivity.class),
                                        0);

                                final String contentText = numUtterances == 1 ? " time!" : " times!";
                                Notification n = new NotificationCompat.Builder(this, CHANNEL_ID)
                                        .setContentTitle("Wake word")
                                        .setContentText("Detected " + numUtterances + contentText)
                                        .setSmallIcon(R.drawable.ic_launcher_background)
                                        .setContentIntent(contentIntent)
                                        .build();

                                NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                                assert notificationManager != null;
                                notificationManager.notify(1234, n);
                            });
            porcupineManager.start();
        } catch (PorcupineException e) {
            Log.e("PORCUPINE", e.toString());
        }
        return super.onStartCommand(intent, flags, startId);
    }

    public void userInputListener(){
        try {
            porcupineManager.stop();
        } catch (PorcupineException e) {
            e.printStackTrace();
        }
        Log.i("check", "true/false");
      //        textSpeechInitialize();
      //        startRecognition();
      //        listening();
      //        speechRecognizer.destroy();

        porcupineManager.start();
    }`

**Comment by laves** [comment] 2021-05-26 18:24
We'll be looking into this shortly - thank you for your patience.

**Comment by VolkerLieber** [comment] 2021-05-26 19:36
Sorry for the long wait time. The problem seems to be that the MicrophoneReader listener loop invokes the callback function on keyword detection and waits for the callback to return before continuing execution (and shutting down if you have called .stop()).
To circumvent this, one could call an asynchronous function in the callback, which waits for microphone access before starting the speech-to-text engine, or if that is a bit too much of a hassle: Try to start the speech-to-text engine without stopping porcupine. I did that using RecognizerIntent, and it seems to takeover microphone rights while in use, thus working as intended.
I am optimistic that this will be fixed soon, but hopefully these insights can help you until then.

**Comment by laves** [comment] 2021-06-08 00:09
@vp2305 the most recent version of the Porcupine Android binding should address this. Please update to porcupine-android:1.9.3. Reopen the issue if needed.

**Closed by laves** 2021-06-08 00:09 UTC
Labels: question
